### ISSUE TITLE
[Feature] Log in system

### ISSUE THREAD

**Issue by anrchen** [anrchen/soen343#4]
(To be confirmed) We may not need a log-in system in the case of our project.

We agree on asking for authentication (student ID number) only when an user reserves a room.

**Comment by anrchen** [comment]
Confirmed that we NEED one. Feature team currently working on it!

**Comment by SaifMahabub** [comment]
Log-in system has been discussed during team meeting and has been confirmed that it is needed for the project.

**Comment by anrchen** [comment]
Log-in and log out system is now done.
